### ISSUE TITLE
Create desktop GUI

### ISSUE THREAD

**Issue by nikhilkumarsingh** [coding-blocks/content-downloader#2]
ctdl currently works as a command line utility.
Create a desktop GUI for ctdl using Tkinter.

**Comment by abhishek97** [comment]
Is using Tkinter compulsory? Can't we use other tools for this? Like electron?https://electron.atom.io

**Comment by nikhilkumarsingh** [comment]
Well, I have no idea if it is easy/possible to integrate python scripts with electron. 
Tkinter is not compulsory though. You can try electron if it is possible.

**Comment by abhishek97** [comment]
It is possible to use electron here. The UI/UX with Tkinter is a bust. 
Heres how it'll go using electron:
1. Write a Python Wrapper to expose the cli as an API for the electron app to consume. (something like zeromq ) 
2. Use electron to server static files (`.html`) and use the api.

In the process we will have a web api for the same as well.

**Comment by nikhilkumarsingh** [comment]
Ok then. Go for it!

**Comment by sourabhtk37** [comment]
Wouldn't that be too complex @abhishek97 ? (`import this`)
(totally keeping aside electron's aspects)
Now, if you are talking about cross platform aspect then why not kivy?

**Comment by sourabhtk37** [comment]
Why the need of desktop GUI than a simple webapp? @nikhilkumarsingh

**Comment by akansh97531** [comment]
#5 gui for content downloader @nikhilkumarsingh
