### ISSUE TITLE
duckduckgo api limitations

### ISSUE THREAD

**Issue by akansh97531** [coding-blocks/content-downloader#9]
@nikhilkumarsingh  i was exploring duckduckgo api , and it turns out it is so limited ::
https://duckduckgo.com/api

i tried the query : "python" and it returned many results,
while query "python filetype:pdf" , returned 0 results

**Comment by nikhilkumarsingh** [comment]
@akansh97531 You will need to scrape their web search results page.
You can follow this: https://github.com/fossasia/query-server/blob/master/app/scraper.py
